# alot config loader is sensitive to leading space !
{ config, lib, pkgs, ... }:

with lib;

let

  cfg = config.programs.aerc;

  # filter (a: a.notmuch.enable)
  aercAccounts = (attrValues config.accounts.email.accounts);

  accountAttr = account: with account;
    { account.name = {
          source        = "imaps://";
          outgoing      = "smtp+plain";
          default       = "INBOX";
          smtp-starttls = "yes";
          from          = "Matthieu coudron <${address}>";
          copy-to       = folders.sent;
          # sendmail_command =
          #   optionalString (alot.sendMailCommand != null) alot.sendMailCommand;
          # sent_box = "maildir" + "://" + maildir.absPath + "/" + folders.sent;
          # draft_box = "maildir" + "://"+ maildir.absPath + "/" + folders.drafts;
        };
      }
      ;

  configFile =
    let
      bindingsToStr = attrSet:
        concatStringsSep "\n" (mapAttrsToList (n: v: "${n} = ${v}") attrSet);
    in
      ''
        # Generated by Home Manager.

        ${cfg.extraConfig}
      ''
      # + (
      #   let
      #   in
      #       generators.toINI {}
      #                       (mapAttrs (name: x: submoduleToAttrs x) cfg.tags)
      # )
      + ''

        ${concatStringsSep "\n\n" (map accountAttr aercAccounts)}
      '';

in

{
  options.programs.aerc = {
    enable = mkEnableOption "Aerc";

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra lines added to alot configuration file.
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages =  [ pkgs.aerc ];

    xdg.configFile."aerc/accounts.conf".text = configFile;

    # xdg.configFile."alot/hooks.py" = mkIf (cfg.hooks != "") {
    #   text = ''
    #     # Generated by Home Manager.
    #   ''
  };
}

